/*
 * Created on 2019-05-07 ( Date ISO 2019-05-07 - Time 19:47:33 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.prodata.controller.dto;

import javax.validation.constraints.NotNull;



/**
 * Hateoas resource associated with FileModel.
 * @author Somesh Biswas version 3.0.0
 */
public class FileModelDTO  {

	// Because id is reserved in parent class, we can't override the getter.
	
		@NotNull
		   private Long id;  
		   private String mimetype;  
		   private String name;  
		   private byte[] pic;  
		   private Long rollNo;  

	// Constructor
	public FileModelDTO() {
		// Needed empty constructor for serialization
	}

	public Long getId() {
		return this.id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public String getMimetype() {
		return this.mimetype;
	}
	public void setMimetype(String mimetype) {
		this.mimetype = mimetype;
	}
	public String getName() {
		return this.name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public byte[] getPic() {
		return this.pic;
	}
	public void setPic(byte[] pic) {
		this.pic = pic;
	}
	public Long getRollNo() {
		return this.rollNo;
	}
	public void setRollNo(Long rollNo) {
		this.rollNo = rollNo;
	}

	public String toString() {
		StringBuilder sb = new StringBuilder(); 
	sb.append("FileModelDTO");
		sb.append("id :");
		sb.append(id); 
		sb.append("mimetype :");
		sb.append(mimetype); 
		sb.append("|"); 
		sb.append("name :");
		sb.append(name); 
		sb.append("|"); 
		sb.append("pic :");
		sb.append(pic); 
		sb.append("|"); 
		sb.append("rollNo :");
		sb.append(rollNo); 
        return sb.toString();
    }

}


