/*
 * Created on 2019-07-08 ( Date ISO 2019-07-08 - Time 15:31:55 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.prodata.controller.dto;

import java.util.Date;
import javax.validation.constraints.NotNull;



/**
 * Hateoas resource associated with Role.
 * @author Somesh Biswas version 3.0.0
 */
public class RoleDTO  {

		@NotNull
		   private Integer roleId;  
		@NotNull
		   private String activeFlag;  
		@NotNull
		   private String authority;  
		   private String createdBy;  
		@NotNull
		   private Date createdDate;  
		@NotNull
		   private String description;  
		@NotNull
		   private String displayName;  
		   private String modifiedBy;  
		@NotNull
		   private Date modifiedDate;  
		@NotNull
		   private Long securityLevel;  

	// Constructor
	public RoleDTO() {
		// Needed empty constructor for serialization
	}

	public Integer getRoleId() {
		return this.roleId;
	}
	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}
	public String getActiveFlag() {
		return this.activeFlag;
	}
	public void setActiveFlag(String activeFlag) {
		this.activeFlag = activeFlag;
	}
	public String getAuthority() {
		return this.authority;
	}
	public void setAuthority(String authority) {
		this.authority = authority;
	}
	public String getCreatedBy() {
		return this.createdBy;
	}
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}
	public Date getCreatedDate() {
		return this.createdDate;
	}
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	public String getDescription() {
		return this.description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public String getDisplayName() {
		return this.displayName;
	}
	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}
	public String getModifiedBy() {
		return this.modifiedBy;
	}
	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}
	public Date getModifiedDate() {
		return this.modifiedDate;
	}
	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}
	public Long getSecurityLevel() {
		return this.securityLevel;
	}
	public void setSecurityLevel(Long securityLevel) {
		this.securityLevel = securityLevel;
	}

	public String toString() {
		StringBuilder sb = new StringBuilder(); 
	sb.append("RoleDTO");
		sb.append("roleId :");
		sb.append(roleId); 
		sb.append("activeFlag :");
		sb.append(activeFlag); 
		sb.append("|"); 
		sb.append("authority :");
		sb.append(authority); 
		sb.append("|"); 
		sb.append("createdBy :");
		sb.append(createdBy); 
		sb.append("|"); 
		sb.append("createdDate :");
		sb.append(createdDate); 
		sb.append("|"); 
		sb.append("description :");
		sb.append(description); 
		sb.append("|"); 
		sb.append("displayName :");
		sb.append(displayName); 
		sb.append("|"); 
		sb.append("modifiedBy :");
		sb.append(modifiedBy); 
		sb.append("|"); 
		sb.append("modifiedDate :");
		sb.append(modifiedDate); 
		sb.append("|"); 
		sb.append("securityLevel :");
		sb.append(securityLevel); 
        return sb.toString();
    }

}


