/*
 * Created on 2019-07-09 ( Date ISO 2019-07-09 - Time 12:12:20 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.prodata.controller.dto;

import javax.validation.constraints.NotNull;



/**
 * Hateoas resource associated with Staff.
 * @author Somesh Biswas version 3.0.0
 */
public class StaffDTO  {

		@NotNull
		   private Long staffId;  
		@NotNull
		   private String staffFname;  
		@NotNull
		   private String staffLname;  
		@NotNull
		   private String loginKey;  
		@NotNull
		   private String loginid;  
		@NotNull
		   private String activeFlag;  

	// Constructor
	public StaffDTO() {
		// Needed empty constructor for serialization
	}

	public Long getStaffId() {
		return this.staffId;
	}
	public void setStaffId(Long staffId) {
		this.staffId = staffId;
	}
	public String getStaffFname() {
		return this.staffFname;
	}
	public void setStaffFname(String staffFname) {
		this.staffFname = staffFname;
	}
	public String getStaffLname() {
		return this.staffLname;
	}
	public void setStaffLname(String staffLname) {
		this.staffLname = staffLname;
	}
	public String getLoginKey() {
		return this.loginKey;
	}
	public void setLoginKey(String loginKey) {
		this.loginKey = loginKey;
	}
	public String getLoginid() {
		return this.loginid;
	}
	public void setLoginid(String loginid) {
		this.loginid = loginid;
	}
	public String getActiveFlag() {
		return this.activeFlag;
	}
	public void setActiveFlag(String activeFlag) {
		this.activeFlag = activeFlag;
	}

	public String toString() {
		StringBuilder sb = new StringBuilder(); 
	sb.append("StaffDTO");
		sb.append("staffId :");
		sb.append(staffId); 
		sb.append("staffFname :");
		sb.append(staffFname); 
		sb.append("|"); 
		sb.append("staffLname :");
		sb.append(staffLname); 
		sb.append("|"); 
		sb.append("loginKey :");
		sb.append(loginKey); 
		sb.append("|"); 
		sb.append("loginid :");
		sb.append(loginid); 
		sb.append("|"); 
		sb.append("activeFlag :");
		sb.append(activeFlag); 
        return sb.toString();
    }

}


