/*
 * Created on 2019-06-04 ( Date ISO 2019-06-04 - Time 14:58:51 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.prodata.controller.dto;

import javax.validation.constraints.NotNull;



/**
 * Hateoas resource associated with StudentMarks.
 * @author Somesh Biswas version 3.0.0
 */
public class StudentMarksDTO  {

	// Because id is reserved in parent class, we can't override the getter.
	
		@NotNull
		   private Integer id;  
		@NotNull
		   private Integer rollno;  
		@NotNull
		   private String year;  
		@NotNull
		   private Long semester;  
		@NotNull
		   private Long subject1;  
		@NotNull
		   private Long subject2;  
		@NotNull
		   private Long subject3;  
		@NotNull
		   private Long total;  
		@NotNull
		   private Long avg;  
		@NotNull
		   private String grade;  

	// Constructor
	public StudentMarksDTO() {
		// Needed empty constructor for serialization
	}

	public Integer getId() {
		return this.id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public Integer getRollno() {
		return this.rollno;
	}
	public void setRollno(Integer rollno) {
		this.rollno = rollno;
	}
	public String getYear() {
		return this.year;
	}
	public void setYear(String year) {
		this.year = year;
	}
	public Long getSemester() {
		return this.semester;
	}
	public void setSemester(Long semester) {
		this.semester = semester;
	}
	public Long getSubject1() {
		return this.subject1;
	}
	public void setSubject1(Long subject1) {
		this.subject1 = subject1;
	}
	public Long getSubject2() {
		return this.subject2;
	}
	public void setSubject2(Long subject2) {
		this.subject2 = subject2;
	}
	public Long getSubject3() {
		return this.subject3;
	}
	public void setSubject3(Long subject3) {
		this.subject3 = subject3;
	}
	public Long getTotal() {
		return this.total;
	}
	public void setTotal(Long total) {
		this.total = total;
	}
	public Long getAvg() {
		return this.avg;
	}
	public void setAvg(Long avg) {
		this.avg = avg;
	}
	public String getGrade() {
		return this.grade;
	}
	public void setGrade(String grade) {
		this.grade = grade;
	}

	public String toString() {
		StringBuilder sb = new StringBuilder(); 
	sb.append("StudentMarksDTO");
		sb.append("id :");
		sb.append(id); 
		sb.append("rollno :");
		sb.append(rollno); 
		sb.append("|"); 
		sb.append("year :");
		sb.append(year); 
		sb.append("|"); 
		sb.append("semester :");
		sb.append(semester); 
		sb.append("|"); 
		sb.append("subject1 :");
		sb.append(subject1); 
		sb.append("|"); 
		sb.append("subject2 :");
		sb.append(subject2); 
		sb.append("|"); 
		sb.append("subject3 :");
		sb.append(subject3); 
		sb.append("|"); 
		sb.append("total :");
		sb.append(total); 
		sb.append("|"); 
		sb.append("avg :");
		sb.append(avg); 
		sb.append("|"); 
		sb.append("grade :");
		sb.append(grade); 
        return sb.toString();
    }

}


