/*
 * Created on 2019-05-30 ( Date ISO 2019-05-30 - Time 14:40:06 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.prodata.controller.dto;

import javax.validation.constraints.NotNull;



/**
 * Hateoas resource associated with StudentRelatives.
 * @author Somesh Biswas version 3.0.0
 */
public class StudentRelativesDTO  {

	// Because id is reserved in parent class, we can't override the getter.
	
		@NotNull
		   private Integer id;  
		@NotNull
		   private String mobNo;  
		@NotNull
		   private String name;  
		@NotNull
		   private String relation;  
		@NotNull
		   private Long rollno;  

	// Constructor
	public StudentRelativesDTO() {
		// Needed empty constructor for serialization
	}

	public Integer getId() {
		return this.id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getMobNo() {
		return this.mobNo;
	}
	public void setMobNo(String mobNo) {
		this.mobNo = mobNo;
	}
	public String getName() {
		return this.name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getRelation() {
		return this.relation;
	}
	public void setRelation(String relation) {
		this.relation = relation;
	}
	public Long getRollno() {
		return this.rollno;
	}
	public void setRollno(Long rollno) {
		this.rollno = rollno;
	}

	public String toString() {
		StringBuilder sb = new StringBuilder(); 
	sb.append("StudentRelativesDTO");
		sb.append("id :");
		sb.append(id); 
		sb.append("mobNo :");
		sb.append(mobNo); 
		sb.append("|"); 
		sb.append("name :");
		sb.append(name); 
		sb.append("|"); 
		sb.append("relation :");
		sb.append(relation); 
		sb.append("|"); 
		sb.append("rollno :");
		sb.append(rollno); 
        return sb.toString();
    }

}


