/*
 * Created on 2019-05-07 ( Date ISO 2019-05-07 - Time 19:47:34 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.prodata.controller.dto;

import javax.validation.constraints.NotNull;



/**
 * Hateoas resource associated with StudentLogin.
 * @author Somesh Biswas version 3.0.0
 */
public class StudentLoginDTO  {

		@NotNull
		   private String loginId;  
		   private String password;  

	// Constructor
	public StudentLoginDTO() {
		// Needed empty constructor for serialization
	}

	public String getLoginId() {
		return this.loginId;
	}
	public void setLoginId(String loginId) {
		this.loginId = loginId;
	}
	public String getPassword() {
		return this.password;
	}
	public void setPassword(String password) {
		this.password = password;
	}

	public String toString() {
		StringBuilder sb = new StringBuilder(); 
	sb.append("StudentLoginDTO");
		sb.append("loginId :");
		sb.append(loginId); 
		sb.append("password :");
		sb.append(password); 
        return sb.toString();
    }

}


