/*
 * Created on 2019-05-30 ( Date ISO 2019-05-30 - Time 14:40:06 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.prodata.controller.dto;

import java.util.Date;
import javax.validation.constraints.NotNull;



/**
 * Hateoas resource associated with StudentData.
 * @author Somesh Biswas version 3.0.0
 */
public class StudentDataDTO  {

		@NotNull
		   private Long rollNo;  
		@NotNull
		   private String activeflag;  
		@NotNull
		   private String address;  
		@NotNull
		   private Date dob;  
		@NotNull
		   private String name;  
		@NotNull
		   private String std;  

	// Constructor
	public StudentDataDTO() {
		// Needed empty constructor for serialization
	}

	public Long getRollno() {
		return this.rollNo;
	}
	public void setRollno(Long rollno) {
		this.rollNo = rollno;
	}
	public String getActiveflag() {
		return this.activeflag;
	}
	public void setActiveflag(String activeflag) {
		this.activeflag = activeflag;
	}
	public String getAddress() {
		return this.address;
	}
	public void setAddress(String address) {
		this.address = address;
	}
	public Date getDob() {
		return this.dob;
	}
	public void setDob(Date dob) {
		this.dob = dob;
	}
	public String getName() {
		return this.name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getStd() {
		return this.std;
	}
	public void setStd(String std) {
		this.std = std;
	}

	public String toString() {
		StringBuilder sb = new StringBuilder(); 
	sb.append("StudentDataDTO");
		sb.append("rollno :");
		sb.append(rollNo); 
		sb.append("activeflag :");
		sb.append(activeflag); 
		sb.append("|"); 
		sb.append("address :");
		sb.append(address); 
		sb.append("|"); 
		sb.append("dob :");
		sb.append(dob); 
		sb.append("|"); 
		sb.append("name :");
		sb.append(name); 
		sb.append("|"); 
		sb.append("std :");
		sb.append(std); 
        return sb.toString();
    }

}


