/*
 * Created on 2019-07-08 ( Date ISO 2019-07-08 - Time 15:31:56 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.prodata.controller.mapper;

import java.util.List;

import com.cpa.prodata.controller.dto.RoleDTO;
import com.cpa.prodata.entity.Role;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
/**
 * RoleDTO's Mapper declaration using selma.
 * @author Somesh Biswas version 3.0.0
 */
@Mapper(componentModel = "spring")
public abstract class RoleMapper {

	// This will build a fresh new RoleDTO with in infos
		
public abstract  RoleDTO convertEntityToRoleDTO(Role entity);
	
public abstract  Role  convertRoleDTOToEntity( RoleDTO dto);



public abstract List<RoleDTO>  entityListToRoleDTOList(List<Role> list);
}
