/*
 * Created on 2019-07-08 ( Date ISO 2019-07-08 - Time 15:31:58 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.prodata.controller.mapper;

import java.util.List;

import com.cpa.prodata.controller.dto.StaffRolesDTO;
import com.cpa.prodata.entity.StaffRoles;
import com.cpa.prodata.repository.StaffRepository;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.springframework.beans.factory.annotation.Autowired;
/**
 * StaffRolesDTO's Mapper declaration using selma.
 * @author Somesh Biswas version 3.0.0
 */
@Mapper(componentModel = "spring")
public abstract class StaffRolesMapper {

	@Autowired
	public StaffRepository staffRepository;
	// This will build a fresh new StaffRolesDTO with in infos
	@Mapping(target = "staffId", expression = "java(entity.getStaff().getStaffId())")	
public abstract  StaffRolesDTO convertEntityToStaffRolesDTO(StaffRoles entity);
	
	@Mapping(target = "staff", expression = "java(staffRepository.findStaff(dto.getStaffId()))")
public abstract  StaffRoles  convertStaffRolesDTOToEntity( StaffRolesDTO dto);



public abstract List<StaffRolesDTO>  entityListToStaffRolesDTOList(List<StaffRoles> list);
}
