/*
 * Created on 2019-05-30 ( Date ISO 2019-05-30 - Time 14:40:06 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.prodata.controller.mapper;

import java.util.List;

import com.cpa.prodata.controller.dto.StudentDataDTO;
import com.cpa.prodata.entity.StudentData;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
/**
 * StudentDataDTO's Mapper declaration using selma.
 * @author Somesh Biswas version 3.0.0
 */
@Mapper(componentModel = "spring")
public abstract class StudentDataMapper {

	// This will build a fresh new StudentDataDTO with in infos
		
public abstract  StudentDataDTO convertEntityToStudentDataDTO(StudentData entity);
	
public abstract  StudentData  convertStudentDataDTOToEntity( StudentDataDTO dto);



public abstract List<StudentDataDTO>  entityListToStudentDataDTOList(List<StudentData> list);
}
