/*
 * Created on 2019-05-30 ( Date ISO 2019-05-30 - Time 14:40:06 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.prodata.controller.mapper;

import java.util.List;

import com.cpa.prodata.controller.dto.StudentRelativesDTO;
import com.cpa.prodata.entity.StudentRelatives;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
/**
 * StudentRelativesDTO's Mapper declaration using selma.
 * @author Somesh Biswas version 3.0.0
 */
@Mapper(componentModel = "spring")
public abstract class StudentRelativesMapper {

	// This will build a fresh new StudentRelativesDTO with in infos
		
public abstract  StudentRelativesDTO convertEntityToStudentRelativesDTO(StudentRelatives entity);
	
public abstract  StudentRelatives  convertStudentRelativesDTOToEntity( StudentRelativesDTO dto);



public abstract List<StudentRelativesDTO>  entityListToStudentRelativesDTOList(List<StudentRelatives> list);
}
