/*
 * Created on 2019-05-30 ( Date ISO 2019-05-30 - Time 14:55:05 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.prodata.controller.mapper;

import java.util.List;

import com.cpa.prodata.controller.dto.StudentMarksDTO;
import com.cpa.prodata.entity.StudentMarks;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
/**
 * StudentMarksDTO's Mapper declaration using selma.
 * @author Somesh Biswas version 3.0.0
 */
@Mapper(componentModel = "spring")
public abstract class StudentMarksMapper {

	// This will build a fresh new StudentMarksDTO with in infos
		
public abstract  StudentMarksDTO convertEntityToStudentMarksDTO(StudentMarks entity);
	
public abstract  StudentMarks  convertStudentMarksDTOToEntity( StudentMarksDTO dto);



public abstract List<StudentMarksDTO>  entityListToStudentMarksDTOList(List<StudentMarks> list);
}
