/*
 * Created on 2019-05-07 ( Date ISO 2019-05-07 - Time 19:47:32 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.prodata.service.criteria;

/**
 * Criteria bean used for FileModel search.
 * @author Somesh Biswas version 3.0.0
 */
public class FileModelCriteria {

    private String mimetype; 
    private String name; 
	// Constructor
	public FileModelCriteria() {
		// Needed empty constructor for serialization
	}

	public void setMimetype(String mimetype) {this.mimetype = mimetype;}
	public String getMimetype() {return this.mimetype;}
	public void setName(String name) {this.name = name;}
	public String getName() {return this.name;}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(mimetype); 
		sb.append("|"); 
		sb.append(name); 
        return sb.toString();
	}
}
