/*
 * Created on 2019-07-08 ( Date ISO 2019-07-08 - Time 15:31:56 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.prodata.service.criteria;

/**
 * Criteria bean used for Staff search.
 * @author Somesh Biswas version 3.0.0
 */
public class StaffCriteria {

    private String staffFname; 
    private String staffLname; 
    private String loginKey; 
    private String staffUsername; 
	// Constructor
	public StaffCriteria() {
		// Needed empty constructor for serialization
	}

	public void setStaffFname(String staffFname) {this.staffFname = staffFname;}
	public String getStaffFname() {return this.staffFname;}
	public void setStaffLname(String staffLname) {this.staffLname = staffLname;}
	public String getStaffLname() {return this.staffLname;}
	public void setLoginKey(String loginKey) {this.loginKey = loginKey;}
	public String getLoginKey() {return this.loginKey;}
	public void setStaffUsername(String staffUsername) {this.staffUsername = staffUsername;}
	public String getStaffUsername() {return this.staffUsername;}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(staffFname); 
		sb.append("|"); 
		sb.append(staffLname); 
		sb.append("|"); 
		sb.append(loginKey); 
		sb.append("|"); 
		sb.append(staffUsername); 
        return sb.toString();
	}
}
