/*
 * Created on 2019-07-08 ( Date ISO 2019-07-08 - Time 15:31:57 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.prodata.service.criteria;

/**
 * Criteria bean used for StaffRoles search.
 * @author Somesh Biswas version 3.0.0
 */
public class StaffRolesCriteria {

    private String authority; 
    private String displayName; 
	// Constructor
	public StaffRolesCriteria() {
		// Needed empty constructor for serialization
	}

	public void setAuthority(String authority) {this.authority = authority;}
	public String getAuthority() {return this.authority;}
	public void setDisplayName(String displayName) {this.displayName = displayName;}
	public String getDisplayName() {return this.displayName;}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(authority); 
		sb.append("|"); 
		sb.append(displayName); 
        return sb.toString();
	}
}
