/*
 * Created on 2019-05-30 ( Date ISO 2019-05-30 - Time 14:40:06 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.prodata.service.criteria;

/**
 * Criteria bean used for StudentRelatives search.
 * @author Somesh Biswas version 3.0.0
 */
public class StudentRelativesCriteria {

    private String mobNo; 
    private String name; 
    private String relation; 
	// Constructor
	public StudentRelativesCriteria() {
		// Needed empty constructor for serialization
	}

	public void setMobNo(String mobNo) {this.mobNo = mobNo;}
	public String getMobNo() {return this.mobNo;}
	public void setName(String name) {this.name = name;}
	public String getName() {return this.name;}
	public void setRelation(String relation) {this.relation = relation;}
	public String getRelation() {return this.relation;}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(mobNo); 
		sb.append("|"); 
		sb.append(name); 
		sb.append("|"); 
		sb.append(relation); 
        return sb.toString();
	}
}
