/*
 * Created on 2019-05-29 ( Date ISO 2019-05-29 - Time 11:31:51 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.prodata.service.criteria;

/**
 * Criteria bean used for StudentMarks search.
 * @author Somesh Biswas version 3.0.0
 */
public class StudentMarksCriteria {

    private String year; 
    private String grade; 
	// Constructor
	public StudentMarksCriteria() {
		// Needed empty constructor for serialization
	}

	public void setYear(String year) {this.year = year;}
	public String getYear() {return this.year;}
	public void setGrade(String grade) {this.grade = grade;}
	public String getGrade() {return this.grade;}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(year); 
		sb.append("|"); 
		sb.append(grade); 
        return sb.toString();
	}
}
