/*
 * Created on 2019-05-07 ( Date ISO 2019-05-07 - Time 19:47:32 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.prodata.entity;
import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;

/**
 * Persistent class for FileModel entity stored in table file_model.
 * This class is a "record entity" without JPA links.
 * @author Somesh Biswas version 3.0.0
 */
@Entity
@Table(name="file_model", schema="public" )
public class FileModel implements Serializable {

	private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue
    @Column(name="id", nullable=false)
    private Long id ;  

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

 
    @Column(name="mimetype", length=255)
private String mimetype ;
 
    @Column(name="name", length=255)
private String name ;
 
    @Lob
    @Column(name="pic")
private byte[] pic ;
 
    @Column(name="roll_no")
private Long rollNo ;


    
    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public FileModel(String name, String mimetype, byte[] pic,Long rollNo){
        this.name = name;
        this.mimetype = mimetype;
        this.pic = pic;
        this.rollNo=rollNo;
      }
    
    public FileModel() {
    	super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
	public void setId(Long id) {
        this.id = id ;
    }
	public Long getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
	//--- DATABASE MAPPING : mimetype (varchar) 
	public void setMimetype(String mimetype)
 {this.mimetype = mimetype;}


	public String getMimetype()
 {return this.mimetype;}


	//--- DATABASE MAPPING : name (varchar) 
	public void setName(String name)
 {this.name = name;}


	public String getName()
 {return this.name;}


	//--- DATABASE MAPPING : pic (bytea) 
	public void setPic(byte[] pic)
 {this.pic = pic;}


	public byte[] getPic()
 {return this.pic;}


	//--- DATABASE MAPPING : roll_no (int8) 
	public void setRollNo(Long rollNo)
 {this.rollNo = rollNo;}


	public Long getRollNo()
 {return this.rollNo;}




    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 	 	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append("FileModel");
		sb.append("id :");
		sb.append(id); 
		sb.append("mimetype :");
		sb.append(mimetype); 
		sb.append("|"); 
		sb.append("name :");
		sb.append(name); 
		sb.append("|"); 
		sb.append("pic :");
		sb.append(pic); 
		sb.append("|"); 
		sb.append("rollNo :");
		sb.append(rollNo); 
        return sb.toString();
    }
}