/*
 * Created on 2019-07-08 ( Date ISO 2019-07-08 - Time 15:31:55 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.prodata.entity;
import java.util.List;
import java.io.Serializable;
import java.util.Date;
import javax.persistence.*;

/**
 * Persistent class for Role entity stored in table role.
 * This class is a "record entity" without JPA links.
 * @author Somesh Biswas version 3.0.0
 */
@Entity
@Table(name="role", schema="public" )
public class Role implements Serializable {

	private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="role_id", nullable=false)
    private Integer roleId ;  

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

 
    @Column(name="active_flag", nullable=false, length=1)
private String activeFlag ;
 
    @Column(name="authority", nullable=false, length=255)
private String authority ;
 
    @Column(name="created_by", length=100)
private String createdBy ;
 
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_date", nullable=false)
private Date createdDate ;
 
    @Column(name="description", nullable=false, length=255)
private String description ;
 
    @Column(name="display_name", nullable=false, length=255)
private String displayName ;
 
    @Column(name="modified_by", length=100)
private String modifiedBy ;
 
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modified_date", nullable=false)
private Date modifiedDate ;
 
    @Column(name="security_level", nullable=false)
private Long securityLevel ;


    
    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Role() {
		super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
	public void setRoleId(Integer roleId) {
        this.roleId = roleId ;
    }
	public Integer getRoleId() {
        return this.roleId;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
	//--- DATABASE MAPPING : active_flag (varchar) 
	public void setActiveFlag(String activeFlag)
 {this.activeFlag = activeFlag;}


	public String getActiveFlag()
 {return this.activeFlag;}


	//--- DATABASE MAPPING : authority (varchar) 
	public void setAuthority(String authority)
 {this.authority = authority;}


	public String getAuthority()
 {return this.authority;}


	//--- DATABASE MAPPING : created_by (varchar) 
	public void setCreatedBy(String createdBy)
 {this.createdBy = createdBy;}


	public String getCreatedBy()
 {return this.createdBy;}


	//--- DATABASE MAPPING : created_date (timestamp) 
	public void setCreatedDate(Date createdDate)
 {this.createdDate = createdDate;}


	public Date getCreatedDate()
 {return this.createdDate;}


	//--- DATABASE MAPPING : description (varchar) 
	public void setDescription(String description)
 {this.description = description;}


	public String getDescription()
 {return this.description;}


	//--- DATABASE MAPPING : display_name (varchar) 
	public void setDisplayName(String displayName)
 {this.displayName = displayName;}


	public String getDisplayName()
 {return this.displayName;}


	//--- DATABASE MAPPING : modified_by (varchar) 
	public void setModifiedBy(String modifiedBy)
 {this.modifiedBy = modifiedBy;}


	public String getModifiedBy()
 {return this.modifiedBy;}


	//--- DATABASE MAPPING : modified_date (timestamp) 
	public void setModifiedDate(Date modifiedDate)
 {this.modifiedDate = modifiedDate;}


	public Date getModifiedDate()
 {return this.modifiedDate;}


	//--- DATABASE MAPPING : security_level (int8) 
	public void setSecurityLevel(Long securityLevel)
 {this.securityLevel = securityLevel;}


	public Long getSecurityLevel()
 {return this.securityLevel;}




    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 	 	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append("Role");
		sb.append("roleId :");
		sb.append(roleId); 
		sb.append("activeFlag :");
		sb.append(activeFlag); 
		sb.append("|"); 
		sb.append("authority :");
		sb.append(authority); 
		sb.append("|"); 
		sb.append("createdBy :");
		sb.append(createdBy); 
		sb.append("|"); 
		sb.append("createdDate :");
		sb.append(createdDate); 
		sb.append("|"); 
		sb.append("description :");
		sb.append(description); 
		sb.append("|"); 
		sb.append("displayName :");
		sb.append(displayName); 
		sb.append("|"); 
		sb.append("modifiedBy :");
		sb.append(modifiedBy); 
		sb.append("|"); 
		sb.append("modifiedDate :");
		sb.append(modifiedDate); 
		sb.append("|"); 
		sb.append("securityLevel :");
		sb.append(securityLevel); 
        return sb.toString();
    }
}