/*
 * Created on 2019-05-31 ( Date ISO 2019-05-31 - Time 16:54:00 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.prodata.entity;
import java.util.List;
import java.io.Serializable;
import javax.persistence.*;

/**
 * Persistent class for StudentRelatives entity stored in table student_relatives.
 * This class is a "record entity" without JPA links.
 * @author Somesh Biswas version 3.0.0
 */
@Entity
@Table(name="student_relatives", schema="public" )
public class StudentRelatives implements Serializable {

	private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer id ;  

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

 
    @Column(name="mob_no", nullable=false, length=2147483647)
private String mobNo ;
 
    @Column(name="name", nullable=false, length=2147483647)
private String name ;
 
    @Column(name="relation", nullable=false, length=255)
private String relation ;
 
    @Column(name="rollno", nullable=false)
private Long rollno ;


    
    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public StudentRelatives() {
		super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
	public void setId(Integer id) {
        this.id = id ;
    }
	public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
	//--- DATABASE MAPPING : mob_no (varchar) 
	public void setMobNo(String mobNo)
 {this.mobNo = mobNo;}


	public String getMobNo()
 {return this.mobNo;}


	//--- DATABASE MAPPING : name (varchar) 
	public void setName(String name)
 {this.name = name;}


	public String getName()
 {return this.name;}


	//--- DATABASE MAPPING : relation (varchar) 
	public void setRelation(String relation)
 {this.relation = relation;}


	public String getRelation()
 {return this.relation;}


	//--- DATABASE MAPPING : rollno (int8) 
	public void setRollno(Long rollno)
 {this.rollno = rollno;}


	public Long getRollno()
 {return this.rollno;}




    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 	 	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append("StudentRelatives");
		sb.append("id :");
		sb.append(id); 
		sb.append("mobNo :");
		sb.append(mobNo); 
		sb.append("|"); 
		sb.append("name :");
		sb.append(name); 
		sb.append("|"); 
		sb.append("relation :");
		sb.append(relation); 
		sb.append("|"); 
		sb.append("rollno :");
		sb.append(rollno); 
        return sb.toString();
    }
}