/*
 * Created on 2019-05-30 ( Date ISO 2019-05-30 - Time 16:17:40 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.prodata.entity;
import java.util.List;
import java.io.Serializable;
import java.util.Date;
import javax.persistence.*;

import org.hibernate.envers.Audited;

/**
 * Persistent class for StudentData entity stored in table student_data.
 * This class is a "record entity" without JPA links.
 * @author Somesh Biswas version 3.0.0
 */
@Entity
@Table(name="student_data", schema="public" )
@Audited
public class StudentData implements Serializable {

	private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="rollno", nullable=false)
    private Long rollno ;  

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

 
    @Column(name="activeflag", nullable=false, length=255)
private String activeflag ;
 
    @Column(name="address", nullable=false, length=255)
private String address ;
 
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dob", nullable=false)
private Date dob ;
 
    @Column(name="name", nullable=false, length=255)
private String name ;
 
    @Column(name="std", nullable=false, length=255)
private String std ;

   

    
    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public StudentData() {
		super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
	public void setRollno(Long rollno) {
        this.rollno = rollno ;
    }
	public Long getRollno() {
        return this.rollno;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
	//--- DATABASE MAPPING : activeflag (varchar) 
	public void setActiveflag(String activeflag)
 {this.activeflag = activeflag;}


	public String getActiveflag()
 {return this.activeflag;}


	//--- DATABASE MAPPING : address (varchar) 
	public void setAddress(String address)
 {this.address = address;}


	public String getAddress()
 {return this.address;}


	//--- DATABASE MAPPING : dob (timestamp) 
	public void setDob(Date dob)
 {this.dob = dob;}


	public Date getDob()
 {return this.dob;}


	//--- DATABASE MAPPING : name (varchar) 
	public void setName(String name)
 {this.name = name;}


	public String getName()
 {return this.name;}


	//--- DATABASE MAPPING : std (varchar) 
	public void setStd(String std)
 {this.std = std;}


	public String getStd()
 {return this.std;}





    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 	 	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append("StudentData");
		sb.append("rollno :");
		sb.append(rollno); 
		sb.append("activeflag :");
		sb.append(activeflag); 
		sb.append("|"); 
		sb.append("address :");
		sb.append(address); 
		sb.append("|"); 
		sb.append("dob :");
		sb.append(dob); 
		sb.append("|"); 
		sb.append("name :");
		sb.append(name); 
		sb.append("|"); 
		sb.append("std :");
		sb.append(std); 
        return sb.toString();
    }
}