/*
 * Created on 2019-06-04 ( Date ISO 2019-06-04 - Time 15:28:23 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.prodata.entity;
import java.util.List;
import java.io.Serializable;
import javax.persistence.*;

/**
 * Persistent class for StudentMarks entity stored in table student_marks.
 * This class is a "record entity" without JPA links.
 * @author Somesh Biswas version 3.0.0
 */
@Entity
@Table(name="student_marks", schema="public" )
public class StudentMarks implements Serializable {

	private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer id ;  

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    
    @Column(name="rollno", nullable=false, length=25)
private Integer rollno ;
 
  
    @Column(name="year", nullable=false, length=25)
private String year ;
 
    @Column(name="semester", nullable=false)
private Long semester ;
 
    @Column(name="subject1", nullable=false)
private Long subject1 ;
 
    @Column(name="subject2", nullable=false)
private Long subject2 ;
 
    @Column(name="subject3", nullable=false)
private Long subject3 ;
 
    @Column(name="total", nullable=false)
private Long total ;
 
    @Column(name="avg", nullable=false)
private Long avg ;
 
    @Column(name="grade", nullable=false, length=4)
private String grade ;
 
    @Column(name="academicyear", nullable=false, length=20)
private String academicyear ;

 
    
    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public StudentMarks() {
		super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
	public void setId(Integer id) {
        this.id = id ;
    }
	public Integer getId() {
        return this.id;
    }

	
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
	//--- DATABASE MAPPING : rollno (int4) 

	

	//--- DATABASE MAPPING : year (varchar) 
	public void setYear(String year)
 {this.year = year;}


	public Integer getRollno() {
		return rollno;
	}

	public void setRollno(Integer rollno) {
		this.rollno = rollno;
	}

	public String getYear()
 {return this.year;}


	//--- DATABASE MAPPING : semester (int8) 
	public void setSemester(Long semester)
 {this.semester = semester;}


	public Long getSemester()
 {return this.semester;}


	//--- DATABASE MAPPING : subject1 (int8) 
	public void setSubject1(Long subject1)
 {this.subject1 = subject1;}


	public Long getSubject1()
 {return this.subject1;}


	//--- DATABASE MAPPING : subject2 (int8) 
	public void setSubject2(Long subject2)
 {this.subject2 = subject2;}


	public Long getSubject2()
 {return this.subject2;}


	//--- DATABASE MAPPING : subject3 (int8) 
	public void setSubject3(Long subject3)
 {this.subject3 = subject3;}


	public Long getSubject3()
 {return this.subject3;}


	//--- DATABASE MAPPING : total (int8) 
	public void setTotal(Long total)
 {this.total = total;}


	public Long getTotal()
 {return this.total;}


	//--- DATABASE MAPPING : avg (int8) 
	public void setAvg(Long avg)
 {this.avg = avg;}


	public Long getAvg()
 {return this.avg;}


	//--- DATABASE MAPPING : grade (varchar) 
	public void setGrade(String grade)
 {this.grade = grade;}


	public String getGrade()
 {return this.grade;}


	//--- DATABASE MAPPING : academicyear (varchar) 
	public void setAcademicyear(String academicyear)
 {this.academicyear = academicyear;}


	public String getAcademicyear()
 {return this.academicyear;}




    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 	 	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append("StudentMarks");
		sb.append("id :");
		sb.append(id); 
		sb.append("|"); 
		sb.append("year :");
		sb.append(year); 
		sb.append("|"); 
		sb.append("semester :");
		sb.append(semester); 
		sb.append("|"); 
		sb.append("subject1 :");
		sb.append(subject1); 
		sb.append("|"); 
		sb.append("subject2 :");
		sb.append(subject2); 
		sb.append("|"); 
		sb.append("subject3 :");
		sb.append(subject3); 
		sb.append("|"); 
		sb.append("total :");
		sb.append(total); 
		sb.append("|"); 
		sb.append("avg :");
		sb.append(avg); 
		sb.append("|"); 
		sb.append("grade :");
		sb.append(grade); 
		sb.append("|"); 
		sb.append("academicyear :");
		sb.append(academicyear); 
        return sb.toString();
    }
}