/*
 * Created on 2019-05-07 ( Date ISO 2019-05-07 - Time 19:47:32 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.prodata.repository;

import java.util.List;

import javax.transaction.Transactional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import com.cpa.prodata.entity.FileModel;

/**
 * Jpa repository for FileModel.
 * @author Somesh Biswas version 3.0.0
 */
@Transactional
@Repository
public interface FileModelRepository  extends JpaRepository<FileModel, Long> {
	
	
String SELECTQUERY="select * from file_model s where s.roll_no = :roll_no "; 
	
	@Query(value=SELECTQUERY,nativeQuery=true)
	List<FileModel> findByRoll(@Param("roll_no")Long roll_no);
}