/*
 * Created on 2019-07-08 ( Date ISO 2019-07-08 - Time 15:31:55 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.prodata.repository;

import com.cpa.prodata.entity.Role;
import com.cpa.prodata.repository.constants.RoleConstants;

import javax.transaction.Transactional;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

/**
 * Jpa repository for Role.
 * @author Somesh Biswas version 3.0.0
 */
@Transactional
@Repository
public interface RoleRepository  extends JpaRepository<Role, Integer> {
	
	
	@Query(value = RoleConstants.FIND_ROLE_BY_AUTH, nativeQuery = true)
	Role findActiveRoleByAuthority(@Param("authority") String authority);
}