/*
 * Created on 2019-07-08 ( Date ISO 2019-07-08 - Time 15:31:56 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.prodata.repository;

import com.cpa.prodata.entity.Staff;
import com.cpa.prodata.repository.constants.StaffMemberConstants;

import java.util.Optional;

import javax.transaction.Transactional;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

/**
 * Jpa repository for Staff.
 * @author Somesh Biswas version 3.0.0
 */
@Transactional
@Repository
public interface StaffRepository  extends JpaRepository<Staff, Long> {
	
	
	@Query(value = StaffMemberConstants.FIND_STAFF_BY_LOGIN_ID, nativeQuery = true)
	Optional<Staff> findByLoginId(@Param("loginId")String loginId);
	
	@Query(value = StaffMemberConstants.Find_STAFF,nativeQuery = true)
	 Staff findStaff(@Param("staffId") Long staffId);

}