/*
 * Created on 2019-07-08 ( Date ISO 2019-07-08 - Time 15:31:57 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.prodata.repository;

import com.cpa.prodata.entity.StaffRoles;
import com.cpa.prodata.repository.constants.StaffRoleRepositoryConstants;

import javax.transaction.Transactional;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

/**
 * Jpa repository for StaffRoles.
 * @author Somesh Biswas version 3.0.0
 */
@Transactional
@Repository
public interface StaffRolesRepository  extends JpaRepository<StaffRoles, Integer> {
	
	
	@Query(value = StaffRoleRepositoryConstants.FIND_BY_STAFF_ID, nativeQuery = true)
	StaffRoles findActiveOneByStaffId(@Param("staffId") Long staffId);
	
	@Query(value = StaffRoleRepositoryConstants.FIND_ALL_STAFF_ROLES_BY_STAFF_ROLE_ID, nativeQuery = true)
	StaffRoles findStaffRoleByStaffRoleId(@Param("staffRoleId") Long staffRoleId);
}