/*
 * Created on 2019-05-30 ( Date ISO 2019-05-30 - Time 14:55:04 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.prodata.repository;

import com.cpa.prodata.entity.StudentMarks;
import javax.transaction.Transactional;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

/**
 * Jpa repository for StudentMarks.
 * @author Somesh Biswas version 3.0.0
 */
@Transactional
@Repository
public interface StudentMarksRepository  extends JpaRepository<StudentMarks, Integer> {}