/*
 * Created on 2019-05-30 ( Date ISO 2019-05-30 - Time 14:40:06 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.prodata.repository;

import java.util.List;

import javax.transaction.Transactional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import com.cpa.prodata.controller.dto.StudentRelativesDTO;
import com.cpa.prodata.entity.StudentRelatives;

/**
 * Jpa repository for StudentRelatives.
 * @author Somesh Biswas version 3.0.0
 */
@Transactional
@Repository
public interface StudentRelativesRepository  extends JpaRepository<StudentRelatives, Integer> {
	
	String QUERY="select r.id,r.name,r.mob_no,r.relation,r.rollno from student_relatives r where r.rollno=:rollno";
	@Query(value=QUERY,nativeQuery=true)
	List<StudentRelatives> findByRoll(@Param("rollno")Long roll);
}