/*
 * Created on 2019-05-07 ( Date ISO 2019-05-07 - Time 19:47:32 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.prodata.service;

import java.util.List;

import com.cpa.prodata.controller.dto.FileModelDTO;


public interface FileModelService {


FileModelDTO persistFileModel(FileModelDTO fileModelDTOpersist) ;


  FileModelDTO retrieveFileModelById(Long id);




	List<FileModelDTO> retrieveAllFileModel();


	FileModelDTO modifyFileModel(FileModelDTO fileModelDTOUpdate) ;

	 public void deleteById(Long id);
	}
