/*
 * Created on 2019-07-08 ( Date ISO 2019-07-08 - Time 15:31:56 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.prodata.service;

import com.cpa.prodata.entity.Staff;
import com.cpa.prodata.controller.dto.StaffDTO;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import java.util.List;

import javax.validation.Valid;


public interface StaffService {


StaffDTO persistStaff(StaffDTO staffDTOpersist) ;


  StaffDTO retrieveStaffById(Long staffId);




	List<StaffDTO> retrieveAllStaff();


	StaffDTO modifyStaff(StaffDTO staffDTOUpdate) ;

	 public void deleteById(Long staffId);
	}
