/*
 * Created on 2019-07-08 ( Date ISO 2019-07-08 - Time 15:31:57 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.prodata.service;

import com.cpa.prodata.entity.StaffRoles;
import com.cpa.prodata.controller.dto.StaffRolesDTO;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import java.util.List;


public interface StaffRolesService {


StaffRolesDTO persistStaffRoles(StaffRolesDTO staffRolesDTOpersist) ;



 StaffRolesDTO retrieveStaffRolesByStaffId(Long staffId);
  StaffRolesDTO retrieveStaffRolesByStaffRoleId(Long staffRoleId);


	List<StaffRolesDTO> retrieveAllStaffRoles();


	StaffRolesDTO modifyStaffRoles(StaffRolesDTO staffRolesDTOUpdate) ;

	
	}
