/*
 * Created on 2019-05-30 ( Date ISO 2019-05-30 - Time 14:40:05 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.prodata.service;

import com.cpa.prodata.entity.StudentData;
import com.cpa.prodata.controller.dto.StudentDataDTO;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import java.util.List;


public interface StudentDataService {


StudentDataDTO persistStudentData(StudentDataDTO studentDataDTOpersist) ;


  StudentDataDTO retrieveStudentDataById(Long rollno);




	List<StudentDataDTO> retrieveAllStudentData();


	StudentDataDTO modifyStudentData(StudentDataDTO studentDataDTOUpdate) ;

	 public void deleteById(Long rollno);
	}
