/*
 * Created on 2019-05-29 ( Date ISO 2019-05-29 - Time 11:31:51 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.prodata.service;

import com.cpa.prodata.entity.StudentMarks;
import com.cpa.prodata.controller.dto.StudentMarksDTO;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import java.util.List;


public interface StudentMarksService {

//
//StudentMarksDTO persistStudentMarks(StudentMarksDTO studentMarksDTOpersist) ;
//
//
//  StudentMarksDTO retrieveStudentMarksById(Integer rollno);
//
//
//
//
//	List<StudentMarksDTO> retrieveAllStudentMarks();
//
//
//	StudentMarksDTO modifyStudentMarks(StudentMarksDTO studentMarksDTOUpdate) ;
//
//	 public void deleteById(Integer rollno);
	}
