/*
 * Created on 2019-05-29 ( Date ISO 2019-05-29 - Time 11:31:51 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.prodata.service;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import com.cpa.prodata.entity.StudentMarks;
import com.cpa.prodata.repository.StudentMarksRepository;
import com.cpa.prodata.controller.dto.StudentMarksDTO;
import com.cpa.prodata.service.criteria.StudentMarksCriteria;
import com.cpa.prodata.service.StudentMarksService;
import com.cpa.prodata.controller.mapper.StudentMarksMapper;
import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;

import org.springframework.data.jpa.domain.Specification;
import org.springframework.stereotype.Service;
import java.util.Collections;
import java.util.List;
/**
 * Service implementation for StudentMarks.
 * @author Somesh Biswas version 3.0.0
 */
@Service
public class StudentMarksServiceImpl implements StudentMarksService {

//private static final Logger LOG = Logger.getLogger(StudentMarksServiceImpl.class);
//
//	@Autowired
//	private StudentMarksRepository studentMarksRepository;
//
//	@Autowired
//	private StudentMarksMapper studentMarksMapper;
//
//	
//		
//
//	public StudentMarksDTO persistStudentMarks(StudentMarksDTO studentMarksDTOpersist){
//	try{
//	if(studentMarksDTOpersist !=null){
//		
//
//	 StudentMarks studentMarks = studentMarksMapper.convertStudentMarksDTOToEntity(studentMarksDTOpersist);
//	 StudentMarks studentMarksIn =  studentMarksRepository.saveAndFlush(studentMarks);
//	return (studentMarksIn !=null) ?  studentMarksMapper.convertEntityToStudentMarksDTO(studentMarksIn) : null;
//	}
//}
//		catch (Exception e){
//			LOG.error("Error while inserting StudentMarks {} ", e);
//		}
//return null;
//	}
//
// public StudentMarksDTO retrieveStudentMarksById(Integer rollno){
//
//	try {
//		
//			StudentMarks studentMarks = studentMarksRepository.findById(rollno).get();
//			return (studentMarks != null) ?  studentMarksMapper.convertEntityToStudentMarksDTO(studentMarks) :null;
//		}
//		catch (Exception e){
//			LOG.error("Error Message",e);
//		}
//		return null;
//	}
//
//public List<StudentMarksDTO> retrieveAllStudentMarks(){
//try {
//List<StudentMarks> studentMarksList = studentMarksRepository.findAll();
//return( studentMarksList != null) ?  studentMarksMapper.entityListToStudentMarksDTOList(studentMarksList) : null;
//		}
//		catch (Exception e){
//			LOG.error("Error message",e);
//		}
//		return Collections.emptyList();
//
//}
//
//public 	StudentMarksDTO modifyStudentMarks(StudentMarksDTO studentMarksDTOUpdate){
//	try{
//	if(studentMarksDTOUpdate !=null){
//					StudentMarks  studentMarks = studentMarksRepository.findById(studentMarksDTOUpdate.getRollno()).get();
//	 StudentMarks studentMarksUpdate =  studentMarksRepository.save(studentMarks);
//	return (studentMarksUpdate !=null) ?  studentMarksMapper.convertEntityToStudentMarksDTO(studentMarksUpdate) : null;
//					
//	}
//}
//	catch (Exception e){
//			LOG.error("Error while updating StudentMarks {} ", e);
//		}
//return null;
//	}
//
//public void deleteById(Integer rollno){
//
//
//
//}



}











